"use client";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import ThreeScene from '@/components/ThreeScene'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Madhav Shroff</title>
        <meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />
        <script src="js/BufferGeometryUtils.js"></script>
        <script src="js/GLTFLoader.js"></script>
        <script src="js/DRACOLoader.js"></script>
        <script src="OrbitControls.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.7.9/dat.gui.min.js" integrity="sha512-WoO4Ih0CDOSLYafy22wZD/mcJ7k0ESLqtQsFa6zFKnEUrbtuGU+GkLtVhgt93xa2qewG5gKEC6CWlN8OaCTSVg==" crossOrigin="anonymous" referrerPolicy="no-referrer"></script>
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <ThreeScene />
      </main>
    </>
  )
}
